# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d010d26dfc6b99eefffef7bccbebeee425ec44a99b309407a47a5999eb2d285f47c4fa8daed2b282fa0379990fe48e4ebe159a002c877385a19701f0db84c644

test:
  secret_key_base: 1364319db745c1e3f5aa2b05d53686999a8f506b9d1c00e20bc57d4c3cec2559c2033aae6a6cca4bf0420703c4c85a28a422ccddd5d9f39196b9d6ca0b2a5655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
